language: python
dist: xenial

cache:
  directories:
  - eggs
  - .npm
  - $ES_HOME

notifications:
  slack:
<<<<<<< HEAD
    secure: hlTj34WpuzQmsyxnUnFEwlAJeDcElshGfgw7oHuicAD83LorBFTc9ap6FhZXI5LFnqEl28FZ9YkJJRl0tFZgaApllrMmNCeK2FfRjnF8XGz2JS6Iiyj+hgWrKHHIbcS2g5R6L2/uzIhdMvCb97cReZckjo9lumYAdXGHY8DJbik=
addons:
  apt:
    packages:
      - oracle-java9-set-default
      - bsdtar
      - graphviz
      - redis-server
env:
  global:
    - secure: |-
        CMKR45ew7fJWfF/rvaFkV4gNhWRDdM4y8wlj5p1qrEzJ214SENg03fjHJr6B
        cvNf7vanTJKnVxpxUK9kH5Tn/uaJZtnbnJYehZ4YKwzbJQEAEJpWvCk4C54O
        7diAxOq7YSxxqA2XdtLydkNlo85BWoucmc0yHEl3weNR9554UmM=
    - secure: |-
        WmE7J5Vxheir50Heuji0JVpEmoYH5iPkLMQFgnocY1UspO1ka1+8M7SOgsUH
        SK5yLKZ/6oJyhlySqqTmCfYy3y/WXRNG76dy1kjVj/DEbx+n6Yu0nElw84ED
        ZR5KkpFMaKLA505soY+4lJc4jRl5u0qwCB1Ad3UgTgfkI4QSaGM=
    - BOTO_CONFIG=tmp/bogusvalue
    - JAVA_HOME=/usr/lib/jvm/java-9-oracle
    - ES_VERSION=5.6.1
    - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.deb
    - PATH="/usr/share/elasticsearch/bin:/usr/lib/postgresql/9.3/bin:$PATH"
    - ES_JAVA_OPTS="-Xms2g -Xmx2g"
matrix:
  include:
    - python: "3.4.3"
      env: BROWSER=Chrome
    - python: "3.4.3"
      env: BROWSER=
=======
    secure: |-
      hlTj34WpuzQmsyxnUnFEwlAJeDcElshGfgw7oHuicAD83LorBFTc9ap6Fh
      ZXI5LFnqEl28FZ9YkJJRl0tFZgaApllrMmNCeK2FfRjnF8XGz2JS6Iiyj+
      hgWrKHHIbcS2g5R6L2/uzIhdMvCb97cReZckjo9lumYAdXGHY8DJbik=

env:
  global:
  - secure: |-
      CMKR45ew7fJWfF/rvaFkV4gNhWRDdM4y8wlj5p1qrEzJ214SENg03fjHJr6B
      cvNf7vanTJKnVxpxUK9kH5Tn/uaJZtnbnJYehZ4YKwzbJQEAEJpWvCk4C54O
      7diAxOq7YSxxqA2XdtLydkNlo85BWoucmc0yHEl3weNR9554UmM=
  - secure: |-
      WmE7J5Vxheir50Heuji0JVpEmoYH5iPkLMQFgnocY1UspO1ka1+8M7SOgsUH
      SK5yLKZ/6oJyhlySqqTmCfYy3y/WXRNG76dy1kjVj/DEbx+n6Yu0nElw84ED
      ZR5KkpFMaKLA505soY+4lJc4jRl5u0qwCB1Ad3UgTgfkI4QSaGM=
  - BOTO_CONFIG=/bogus/value # see: https://github.com/boto/boto/issues/3263
  - ES_VERSION=6.6.2
  - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  - ES_JAVA_OPTS="-Xms2g -Xmx2g -XX:+DisableExplicitGC"
  - ES_HOME="$TRAVIS_BUILD_DIR/elasticsearch-${ES_VERSION}"
  - PATH="$ES_HOME/bin:/usr/lib/postgresql/11/bin:$PATH"

>>>>>>> All lrowe py37 updates
before_install:
- |
  if test ! -f "$ES_HOME/bin/elasticsearch"; then
    wget -q ${ES_DOWNLOAD_URL}
    tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  fi
- java --version
- postgres --version
- elasticsearch --version
- initdb --version
- nvm install 10
- node --version
- npm config set python /usr/bin/python2.7
- pip install -U zc.buildout setuptools redis
- gem install compass

install:
<<<<<<< HEAD
  - buildout bootstrap
  - bin/buildout -c buildout-travis.cfg || (echo "Retrying buildout" && bin/buildout -c buildout-travis.cfg)
  - sudo chown -R travis /etc/elasticsearch
before_script:
  - >
    if test -n "$BROWSER"; then
      CONNECT_URL=https://saucelabs.com/downloads/sc-4.5.3-linux.tar.gz
      CONNECT_DOWNLOAD=sc.tar.gz
      SC_READYFILE=sauce-connect-ready-$RANDOM
      SC_LOGFILE=$HOME/sauce-connect.log
      SC_PIDFILE=$HOME/sauce-connect.pid
      curl $CONNECT_URL > $CONNECT_DOWNLOAD
      mkdir sc
      tar -zxf $CONNECT_DOWNLOAD --strip 1 --directory sc
      sc/bin/sc --readyfile $SC_READYFILE \
        --logfile $SC_LOGFILE \
        --pidfile $SC_PIDFILE \
        --tunnel-identifier $TRAVIS_JOB_NUMBER \
        --user $SAUCE_USERNAME --api-key $SAUCE_ACCESS_KEY > /dev/null &
      while test -f "$SC_PIDFILE" && test ! -f "$SC_READYFILE"; do sleep .5; done
    fi
script:
  - if test -z "$BROWSER"; then npm test; fi
  - if test -z "$BROWSER"; then bin/test -v -v --timeout=400 -m "not bdd"; fi
  - >
    if test -n "$BROWSER"; then
      test -f "$SC_PIDFILE" && bin/test -v -v --timeout=400 -m "bdd" --tb=short \
        --splinter-implicit-wait 10 \
=======
- buildout bootstrap
- bin/buildout -c buildout-travis.cfg || (echo "Retrying buildout" && bin/buildout -c buildout-travis.cfg)

matrix:
  include:
  - python: '3.7'
    addons:
      apt:
        packages:
        - bsdtar
        - graphviz
        - redis-server
        - postgresql-11
        - postgresql-client-11
        - postgresql-server-dev-11
    script:
    - npm test
    - bin/test -v -v --timeout=400 -m "not bdd"
  - python: '3.7'
    env: BROWSER=Chrome
    addons:
      sauce_connect: true
      apt:
        packages:
        - bsdtar
        - graphviz
        - redis-server
        - postgresql-11
        - postgresql-client-11
        - postgresql-server-dev-11
    script:
    - |
      bin/test -v -v --timeout=400 -m "bdd" --tb=short \
        --splinter-implicit-wait 20 \
>>>>>>> All lrowe py37 updates
        --splinter-webdriver remote \
        --splinter-remote-url "https://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com/wd/hub" \
        --splinter-socket-timeout 300 \
        --browser-arg tunnel-identifier "$TRAVIS_JOB_NUMBER" \
        --browser-arg-int build  "$TRAVIS_BUILD_NUMBER" \
        --browser-arg-int idleTimeout 300 \
        --browser-arg-int maxDuration 3000 \
        --browser-arg name "$TRAVIS_REPO_SLUG $TRAVIS_BRANCH $TRAVIS_COMMIT" \
        --browser-arg browser "$BROWSER" \
        --browser-arg platform "Linux"
